import { Link } from 'react-router-dom'
import { formatDate, formatNumber } from '../services/sigardData'
import { BacktestChart, MethodNotice, PageIntro, RiskMap, StatCard, TopRadios } from '../components/SigardComponents'

export default function Dashboard({ data }) {
  const { summary } = data
  return <div className="content-wrap"><PageIntro eyebrow="Panel operativo · semana epidemiológica 25" title="Resumen territorial"><p>Predicción de riesgo relativo de dengue para los radios censales de La Rioja Capital (Departamento Capital, La Rioja).</p></PageIntro><MethodNotice>{summary.methodological_warning}</MethodNotice><section className="stat-grid"><StatCard label="Radios analizados" value={summary.number_of_radios} detail="Departamento Capital, La Rioja" accent="blue" /><StatCard label="Casos predichos" value={formatNumber(summary.predicted_cases_radio_sum, 2)} detail="Suma de predicciones por radio" accent="green" /><StatCard label="Modelo" value="Random Forest" detail={`Versión ${summary.model.version}`} accent="gold" /><StatCard label="Corte de datos" value={formatDate(summary.cutoff_date)} detail={`Objetivo: ${formatDate(summary.prediction_week.start)}`} accent="red" /></section><section className="section-heading"><div><span className="eyebrow">Vista territorial</span><h2>Distribución del riesgo por radio</h2></div><Link className="text-link" to="/mapa">Abrir mapa completo →</Link></section><RiskMap geojson={data.geojson} compact /><section className="bottom-grid"><div className="panel"><div className="section-heading"><div><span className="eyebrow">Prioridad de seguimiento</span><h2>Radios con mayor predicción</h2></div><Link className="text-link" to="/mapa">Ver todos</Link></div><TopRadios radios={summary.top_predicted_radios} /></div><div className="panel"><div className="section-heading"><div><span className="eyebrow">Desempeño temporal</span><h2>Backtesting del modelo</h2></div><Link className="text-link" to="/validacion">Ver validación</Link></div><BacktestChart weeks={data.backtest.weeks} /></div></section></div>
}

