import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { formatDate, formatDateRange, formatNumber, getDisclaimer, getExperimentalCollection, getSelectedPrediction, getSelectedWeek } from '../services/sigardData'
import { MethodNotice, PageIntro, StatCard, TemporalControls, TerritorialMap, TopRadios } from '../components/SigardComponents'

export default function Dashboard({ data, selectedCutoffDate, onCutoffChange }) {
  const [territorialView, setTerritorialView] = useState('context')
  const selectedWeek = getSelectedWeek(data, selectedCutoffDate)
  const prediction = getSelectedPrediction(data, selectedCutoffDate)
  const simulation = useMemo(() => getExperimentalCollection(data, selectedCutoffDate), [data, selectedCutoffDate])
  const geojson = territorialView === 'context' ? data.territorialContext : simulation
  const disclaimer = territorialView === 'context' ? getDisclaimer(data.metadata, 'territorial_context') : `${getDisclaimer(data.metadata, 'experimental_spatial')} No representa casos observados ni una predicción espacial validada.`
  const title = territorialView === 'context' ? 'Contexto territorial relativo' : 'Simulación espacial experimental'
  return <div className="content-wrap"><PageIntro eyebrow="Panel operativo" title="Resumen SIGARD"><p>Predicción temporal departamental y exploración territorial del Departamento Capital, La Rioja.</p></PageIntro><TemporalControls weeks={data.availableWeeks.weeks} selectedCutoffDate={selectedCutoffDate} onCutoffChange={onCutoffChange} selectedWeek={selectedWeek} territorialView={territorialView} onViewChange={setTerritorialView} /><section className="stat-grid"><StatCard label="Semana objetivo" value={formatDateRange(selectedWeek.target_week_start, selectedWeek.target_week_end)} detail="Semana epidemiológica siguiente" accent="blue" /><StatCard label="Casos esperados en Capital" value={formatNumber(prediction.predicted_cases_rounded, 0)} detail={`Predicción temporal Random Forest · Estimación continua: ${formatNumber(prediction.predicted_cases, 2)}`} accent="green" /><StatCard label="Radios analizados" value={data.territorialContext.features.length} detail="Departamento Capital, La Rioja" accent="gold" /><StatCard label="Corte de datos" value={formatDate(selectedCutoffDate)} detail={data.temporalPredictions.model.variant} accent="red" /></section><MethodNotice>{disclaimer}</MethodNotice><section className="section-heading"><div><span className="eyebrow">Vista territorial</span><h2>{title}</h2></div><Link className="text-link" to="/mapa">Abrir mapa completo →</Link></section><TerritorialMap geojson={geojson} view={territorialView} disclaimer={disclaimer} compact /><section className="panel"><div className="section-heading"><div><span className="eyebrow">Clasificación relativa</span><h2>{territorialView === 'context' ? 'Mayor contexto territorial relativo' : 'Mayor índice espacial experimental'}</h2></div></div><TopRadios geojson={geojson} view={territorialView} /></section></div>
}
